### PR TITLE
preliminary pull request with first two task implemented

### PR DESCRIPTION
**Pull request by abhishekdd**
Creating this pull request to make the work done so far available for review.
Reading up on WebSockets in Vert.x docs before starting with the final task.

### CODE REVIEW

**Comment by tsegismont** [comment]
I've updated the workflow file, which was testing main branch pushes only. Can you please rebase the PR? Thank you.

**Comment by tsegismont** [comment]
You have closed the PR, is it on purpose?

**Comment by abhishekdd** [comment]
I was trying to rebase and rearrange the commits to include one commit per task. Seems I did something weird to cause it to close automatically.

Tomorrow morning, I will try to reopen it if possible, or create a new one.

**Comment by abhishekdd** [comment]
> You have closed the PR, is it on purpose?

I was trying to rebase and rearrange the commits to include one commit per task. Seems I did something weird to cause it to close automatically.

Tomorrow morning, I will try to reopen it if possible, or create a new one.

**Comment by tsegismont** [comment]
OK, thank you for the udpate

**Pull request closed without merging**
